services:
  HeimrichHannot\HeadBundle\EventListener\Contao\:
    resource: '../../EventListener/Contao/*'
    autowire: true
    autoconfigure: true
    bind:
      $bundleConfig: '%huh_head%'

  huh.head.tag_manager:
    class: HeimrichHannot\HeadBundle\Manager\TagManager
    public: true
    autowire: true
  HeimrichHannot\HeadBundle\Manager\TagManager: '@huh.head.tag_manager'