services:
  _defaults:
    autowire: true
    autoconfigure: true

  HeimrichHannot\HeadBundle\:
    resource: '../../{EventListener,Helper}/*'
    exclude: '../../Helper/LegacyHelper.php'
    bind:
      $bundleConfig: '%huh_head%'

  HeimrichHannot\HeadBundle\Manager\HtmlHeadTagManager:
    public: true
    autoconfigure: false

  huh.head.tag_manager:
    class: HeimrichHannot\HeadBundle\Manager\TagManager
    public: true
  HeimrichHannot\HeadBundle\Manager\TagManager: '@huh.head.tag_manager'