services:
  _defaults:
    autowire: true
    autoconfigure: true

  HeimrichHannot\HeadBundle\:
    resource: '../src/{EventListener,Helper,Twig}/*'
    exclude: '../src/Helper/LegacyHelper.php'
    bind:
      $bundleConfig: '%huh_head%'

  HeimrichHannot\HeadBundle\Manager\:
    resource: '../src/Manager/*'
    public: true
    autoconfigure: false

  HeimrichHannot\HeadBundle\HeadTag\HeadTagFactory:
    autoconfigure: true

  huh.head.tag_manager:
    class: HeimrichHannot\HeadBundle\Manager\TagManager
    public: true
    deprecated: ~
  HeimrichHannot\HeadBundle\Manager\TagManager: '@huh.head.tag_manager'