services:
  _defaults:
    autowire: true
    autoconfigure: true

  HeimrichHannot\HeadBundle\:
    resource: '../src/{EventListener,Helper}/*'
    bind:
      $bundleConfig: '%huh_head%'

  HeimrichHannot\HeadBundle\Manager\:
    resource: '../src/Manager/*'
    public: true
    autoconfigure: false

  HeimrichHannot\HeadBundle\HeadTag\HeadTagFactory:
    autoconfigure: true
